project:
  type: website
  resources:
    - "pdf/*.pdf"

website:
  title: "Home"  
  sidebar:
    search: false
    header: "header.md"
    style: "floating"
    collapse-level: 2
    contents:
         - section: "Agendas"
           contents:
             - text: W1 Content
               file: w1-content.qmd
             - text: W2 Algorithm
               file: w2-algorithm.qmd
             - text: W3 Chatbots
               file: w3-chatbots.qmd
             - text: W4 Nerds
               file: w4-nerds.qmd
             - text: W5 Witness
               file: w5-witness.qmd
             - text: W6 Girl
               file: w6-girl.qmd
         #- section: "Resources"
          # contents:
           #  - text: ChatGPT
            #   href: https://openai.com
  navbar:
    background: "#235440"
    right:
      - icon: github
        aria-label: github
        href: https://github.com/mroberts1/fsu-smt-su24
      - icon: twitter
        aria-label: twitter
        href: https://twitter.com/mroberts_fsu
format:
  html:
    toc: true
    toc-depth: 2
    toc-location: right
    toc-title: '   '
    theme:
      light: [ember.scss, custom_callouts.scss]
      dark: [ember.scss, custom_callouts.scss, slate]
    css: custom.scss
    self-contained: true
    grid:
      sidebar-width: 200px
      body-width: 600px
      margin-width: 200px
      gutter-width: 2em   
    linestretch: 1.5
    fontsize: 1.1em
    smooth-scroll: true
    # linkcolor: "#235440"/
    other-links:
     - text: "Reddit"
       href: https://www.reddit.com/
     - text: "Y Combinator"
       href: https://www.ycombinator.com/
     - text: "Paul Graham"
       href: https://paulgraham.com/articles.html
     - text: "Google Deepmind"
       href: https://deepmind.com
     - text: ChatGPT
       href: https://openai.com
     - text: Claude
       href: https://claude.ai
     - text: Perplexity
       href: https://perplexity.ai
     - text: Gemini
       href: https://gemini.google.com
     - text: Midjourney
       href: https://midjourney.com
     - text: Runway
       href: https://runwayml.com
     - text: Suno
       href: https://suno.com
    link-external-newwindow: true
  PrettyPDF-pdf: default
callout-appearance: default
fig-responsive: true
image-alt: " "
execute:
  freeze: auto
reference-location: margin
citation-location: margin
editor: visual
